CREATE TABLE [dbo].[tblShortURL_Access](
	[idShortURL_Access] [int] IDENTITY(1,1) NOT NULL,
	[ShortURL] [varchar](50) NULL,
	[dtAccess] [datetime] NULL,
 CONSTRAINT [PK_tblShortURL_Access] PRIMARY KEY CLUSTERED 
(
	[idShortURL_Access] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
